"""Builds the downloadable PDF claim report for ClaimPilot."""
from fpdf import FPDF

NAVY = (30, 41, 59)
LIGHT_GRAY = (241, 245, 249)
BORDER_GRAY = (203, 213, 225)
TEXT_GRAY = (100, 116, 139)
INK = (20, 20, 20)
FLAG_COLORS = {
    "consistent": (22, 163, 74),
    "minor mismatch": (217, 119, 6),
    "significant mismatch": (220, 38, 38),
}


class ClaimReportPDF(FPDF):
    def header(self):
        self.set_fill_color(*NAVY)
        self.rect(0, 0, self.w, 24, style="F")
        self.set_xy(10, 7)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "ClaimPilot  |  AI Claim Report", ln=True)
        self.set_y(30)
        self.set_text_color(*INK)

    def footer(self):
        self.set_y(-15)
        self.set_draw_color(*BORDER_GRAY)
        self.line(10, self.get_y(), self.w - 10, self.get_y())
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*TEXT_GRAY)
        self.set_x(10)
        self.cell(0, 10, f"Generated by ClaimPilot AI Co-Pilot   |   Page {self.page_no()}")

    def section_header(self, title):
        self.ln(3)
        self.set_x(10)
        self.set_fill_color(*LIGHT_GRAY)
        self.set_text_color(*NAVY)
        self.set_font("Helvetica", "B", 12)
        self.cell(0, 9, f"  {title}", fill=True, ln=True)
        self.set_text_color(*INK)
        self.set_font("Helvetica", "", 10)
        self.ln(2)

    def kv_line(self, label, value):
        self.set_x(10)
        self.set_font("Helvetica", "B", 10)
        self.write(6, f"{label} ")
        self.set_font("Helvetica", "", 10)
        self.write(6, str(value))
        self.ln(8)

    def paragraph(self, text):
        self.set_x(10)
        self.set_font("Helvetica", "", 10)
        self.multi_cell(0, 6, text)
        self.ln(1)

    def badge(self, text, color):
        self.set_x(10)
        self.set_fill_color(*color)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 10)
        width = self.get_string_width(text) + 10
        self.cell(width, 8, f" {text} ", fill=True, ln=True)
        self.set_text_color(*INK)


def build_report(result: dict, decision_record: dict) -> bytes:
    pdf = ClaimReportPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*TEXT_GRAY)
    pdf.set_x(10)
    pdf.cell(0, 6, f"Report generated: {decision_record['timestamp']}", ln=True)
    pdf.set_text_color(*INK)

    pdf.section_header("Damage Assessment  (CNN + Grad-CAM)")
    pdf.kv_line("Predicted severity:", result["severity"])
    pdf.kv_line("Model confidence:", f"{result['confidence']:.0%}")
    pdf.ln(1)

    overlay_img = result["overlay_img"]
    img_w = 85
    img_h = img_w * overlay_img.height / overlay_img.width
    img_x, img_y = 10, pdf.get_y()
    pdf.image(overlay_img, x=img_x, y=img_y, w=img_w)
    pdf.set_draw_color(*BORDER_GRAY)
    pdf.rect(img_x, img_y, img_w, img_h)
    pdf.ln(img_h + 4)

    pdf.section_header("Risk Assessment  (ANN)")
    pdf.kv_line("Estimated fraud/review risk:", f"{result['risk_score']:.0%}")

    pdf.section_header("AI Reasoning Summary  (Gemini)")
    gemini = result["gemini"]
    pdf.paragraph(gemini["summary"])

    pdf.set_x(10)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, "Consistency check:", ln=True)
    flag_color = FLAG_COLORS.get(gemini["consistency_flag"], TEXT_GRAY)
    pdf.badge(gemini["consistency_flag"].upper(), flag_color)
    pdf.ln(2)

    pdf.set_x(10)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, "Recommendation for adjuster:", ln=True)
    pdf.paragraph(gemini["recommendation"])

    pdf.section_header("Human-in-the-Loop Decision")
    pdf.kv_line("Decision:", decision_record["decision"])
    pdf.kv_line("Adjuster comment:", decision_record.get("comment") or "(none)")
    pdf.kv_line("Decision timestamp:", decision_record["timestamp"])

    return bytes(pdf.output())
